# Generated by Django 6.0.3 on 2026-09-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_delete_order_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('non_veg', 'Non-Veg')], default='veg', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starters', 'Starters'), ('soups', 'Soups'), ('shawarma', 'Shawarma Fest'), ('mandhi', 'Mandhi'), ('main_course', 'Main Course'), ('desserts', 'Desserts'), ('beverages', 'Beverages')], default='starters', max_length=30),
        ),
    ]
