# Generated by Django 6.0.3 on 2026-09-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_menuitem_food_type_alter_menuitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starters', 'Starters'), ('soups', 'Soups'), ('shawarma', 'Shawarma Fest'), ('biryani', 'Biryani'), ('meals', 'Meals'), ('mandhi', 'Mandhi'), ('main_course', 'Main Course'), ('desserts', 'Desserts'), ('beverages', 'Beverages')], default='starters', max_length=30),
        ),
    ]
