# Generated by Django 6.0.3 on 2026-09-26 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
