# Generated by Django 6.0.3 on 2026-09-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_reservation_occasion_alter_reservation_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={},
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('non-veg', 'Non-Veg')], default='veg', max_length=10),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
