# Generated by Django 6.0.3 on 2026-09-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_menuitem_options_alter_menuitem_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='email',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.CharField(choices=[('starters', 'Starters'), ('soups', 'Soups'), ('shawarma', 'Shawarma'), ('biryani', 'Biryani'), ('meals', 'Meals'), ('mandhi', 'Mandhi'), ('main_course', 'Main Course'), ('desserts', 'Desserts'), ('beverages', 'Beverages')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(blank=True, choices=[('birthday', 'Birthday'), ('anniversary', 'Anniversary'), ('date', 'Date'), ('family', 'Family'), ('business', 'Business'), ('other', 'Other')], max_length=30),
        ),
    ]
