# Generated by Django 6.0.3 on 2026-09-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_category_menuitem_image_url_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_food_type',
            field=models.BooleanField(default=True, help_text='Show the Veg / Non-veg marker. Untick for Drinks and Desserts.'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('egg', 'Egg'), ('nonveg', 'Non-veg')], default='veg', max_length=6),
        ),
    ]
