# Generated by Django 6.0.3 on 2026-09-29 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0011_category_show_food_type_menuitem_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='food_type',
            field=models.CharField(choices=[('veg', 'Veg'), ('nonveg', 'Non-veg')], default='veg', max_length=6),
        ),
    ]
